name: Python CI


on:
push:
branches: [ main, master ]
pull_request:
branches: [ main, master ]


jobs:
test:
runs-on: ubuntu-latest


strategy:
matrix:
python-version: [3.10, 3.11]


steps:
- uses: actions/checkout@v4
- name: Set up Python ${{ matrix.python-version }}
uses: actions/setup-python@v4
with:
python-version: ${{ matrix.python-version }}


- name: Install dependencies
run: |
python -m pip install --upgrade pip
if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


- name: Run smoke tests
run: |
python -c "import numpy, pandas, matplotlib; print('imports ok')"


- name: Run lint (optional)
if: false
run: |
pip install flake8
flake8 .
